### ISSUE TITLE
Building BasiliskII on Linux Aarch64 (PineBook Pro)

### ISSUE THREAD

**Issue by oaguy1** [kanjitalk755/macemu#64] opened 2020-10-27 18:23 UTC
Hello!

I posted over on [a forum thread at emaculation](https://www.emaculation.com/forum/viewtopic.php?f=6&t=10886) about building BasiliskII on a linux aarch64 machine. 

I had to update the automake `config.guess` and `config.sub` files in order to properly run the `./configure` script, you can find my changes [here](https://github.com/oaguy1/macemu/tree/fix-aarch64). Once I ran the `./configure` script (with these flags: `--enable-sdl-video --enable-sdl-audio --disable-vosf --enable-jit-compiler=no`), I am able  to build successfully. However, upon lauching the BasiliskII binary, I get the error `ERROR: Not enough free memory.` no matter how much memory I have available. 

I did some digging and the error seems to come from line 645 in src/Unix/main_unix.cpp. There is a failed call to vm_acquire_mac. I put the function definition below:

```c
// NOTE: VM_MAP_32BIT is only used when compiling a 64-bit JIT on specific platforms
void *vm_acquire_mac(size_t size)
{
        return vm_acquire(size, VM_MAP_DEFAULT | VM_MAP_32BIT);
}
```

Below is the output of running uname -a on my machine:

```
Linux [HOSTNAME REDACTED] 5.8.14-1-MANJARO-ARM #1 SMP Wed Oct 7 09:18:37 CEST 2020 aarch64 GNU/Linux
```

Does anybody have any leads on how to fix this?

**Comment by kanjitalk755** [comment] 2020-10-28 04:01
I don't have an aarch64 machine so I can only guess the cause of the problem.
Try following branch:
https://github.com/kanjitalk755/macemu/tree/test_issue64

**Comment by codeandcreate** [comment] 2020-11-17 16:34
This looks good! I could successfully compile and run BasiliskII with your patches and @oaguy1 's two extended configs on aarch64! 👍
![shot-2020-11-17_17-33-18](https://user-images.githubusercontent.com/22428204/99418297-281fb100-28fb-11eb-904d-2f45fc783774.jpg)

**Comment by kanjitalk755** [comment] 2020-11-18 03:05
Merged to the master.

**Closed by kanjitalk755** 2020-11-18 03:05 UTC
