### ISSUE TITLE
Add missing generic_disk support

### ISSUE THREAD

**Issue by gingerbeardman** [kanjitalk755/macemu#167] opened 2023-08-02 10:45 UTC
> **Allow generic_disk implementations to support mountable media**
> 
> Will allow CD-ROM images to be mounted without restarting the emulator.

- https://github.com/mihaip/macemu/commit/91f06fdea8d2cc2e921ba9c482a765c70da94e4d
- https://github.com/mihaip/infinite-mac/commit/401ec13fafe35372c674a38a2e16e873ba53c528

Would also fix the issue where CD-ROMs cannot currently be ejected successfully.

**Comment by RonaldPR** [comment] 2023-08-02 13:13
Can you explain how the user can use this?
For both SheepShaver and BasiliskII?
For all host systems?

**Comment by gingerbeardman** [comment] 2023-08-03 19:31
It depends on how the emulator implemented things, but in Infinite Mac implementation of BasiliskII it would be drag and drop onto the emulated system window. I would expect the same user experience for both emulators and all host systems, but the final decision is with the developer.

But, more important than how the discs can be mounted this change would solve one annoying bug: ejecting a CD-ROM does not currently work on BasiliskII desktop version. Instead, it is kind-of half ejected but then is remounted as a broken sort of weird Audio CD. This change would fix that issue and allow the disc to be truly ejected and not come back.

**Comment by kanjitalk755** [comment] 2023-08-04 08:43
Due to the lack of knowledge about drive management on classic Mac OS and emulators, there is no plan to implement this at this time.

**Comment by gingerbeardman** [comment] 2023-08-04 13:29
Maybe I'm misunderstanding...

...the required code is in the link in the OP? 

The thinking/knowledge/implementation has already been done.

**Comment by kanjitalk755** [comment] 2023-08-05 09:29
> The thinking/knowledge/implementation has already been done.

Yes, but it's based on web technologies, so it can't be merged.

**Comment by gingerbeardman** [comment] 2023-08-05 14:28
I understand.

**Comment by kanjitalk755** [comment] 2023-08-06 12:03
I tried to implement it.

https://github.com/kanjitalk755/macemu/tree/drop_mount

Limitations:

- It cannot be used together with real CD-ROM media.

- Only one image can be dynamically mounted.
   Eject currently mounted image before mounting new one.

**Comment by RonaldPR** [comment] 2023-08-06 13:39
Tried it with a macOS build In Ventura.

Mounting by dragging into the BasiliskII window works and ejecting by dragging to the Trash also works.

Ejecting from the Special menu does not work.

It seems to work with all compatible disk images, not only CD images. All images will be mounted read-only, most with a CD icon.

One disk image I tried worked once but subsequently became unreadable, also when added as disk in the prefs file. Yesterdays backup of the file again worked. I do not know what I did specifically with the image file that could cause it to become unreadable.

This feature is for BasiliskII only? The issue with unmounting CD-images is also present in SheepShaver.

**Comment by cat7** [comment] 2023-08-06 19:01
Gave this a go in Windows too. Works as Ronald describes. As mounting real CDs in Windows works, no additional disk appears when a real CD is already mounted.

**Comment by kanjitalk755** [comment] 2023-08-07 01:33
Fixed a bug that made the current CD-ROM unreadable if you tried to mount new image without ejecting current one.

@RonaldPR

> Ejecting from the Special menu does not work.

The emulator ejects normally, but the behavior on the Finder seems to be different.
Uncorrectable.

> It seems to work with all compatible disk images, not only CD images. All images will be mounted read-only, most with a CD icon.

It is possible to limit the image to be mounted to CD-ROM only, but if possible, it is mounted read-only.

> One disk image I tried worked once but subsequently became unreadable, also when added as disk in the prefs file. Yesterdays backup of the file again worked. I do not know what I did specifically with the image file that could cause it to become unreadable.

This change doesn't affect the `disk` in the prefs.

> This feature is for BasiliskII only? The issue with unmounting CD-images is also present in SheepShaver.

Both BII and SS, for macOS, Linux and Windows.

@cat7

> As mounting real CDs in Windows works, no additional disk appears when a real CD is already mounted.

This is a specification.

**Comment by kanjitalk755** [comment] 2023-08-08 07:57
> Maybe I should explain more clearly. None of the images I tried was at that time mounted through the prefs file. One image mounted fine with this new feature, but when I tried the same file again later, it did not mount. I then tried if adding it to the prefs file would mount it, but also that failed. When I replaced the file with a recent (less than 24 hours) backup, it mounted again fine both ways.

I fixed cdrom.cpp once on the way, could you try to reproduce it with the latest source?
The dropped image file is opened with read-only option, so it shouldn't be broken...

**Comment by RonaldPR** [comment] 2023-08-08 08:40
I will try both BasiliskII and SheepShaver from the latest source later this week

**Comment by RonaldPR** [comment] 2023-08-10 15:22
I tested both BasiliskII and SheepShaver builds for macOS on Ventura.

In both this works as intended. One image file can be mounted as CD by dropping it inside the emulator window.

Both will also mount a dropped image file when one or more other image files are already mounted as CD-ROM through the prefs settings (using "cdrom" instead of "disk").

In SheepShaver with MacOS 9.0.4 and in BasiliskII with MacOS 8.1, one can use any method to remove the dropped "CD" (Trash, Special menu, contextual menu).
In BasiliskII with System 7.5.3 and in SheepShaver with System 7.5.5 one can only remove the "CD" by dragging it to the Trash.
This behaviour apparently depends on the System/MacOS version (or possible the Finder version). The behaviour is similar to when a (floppy) disk is ejected without first removing it from the desktop and the disk needs to be inserted again to be removed properly.
I do not know at which MacOS version the behaviour changed. Could be 7.6 or 8.0.

I did not see disks becoming unreadable.

**Comment by RonaldPR** [comment] 2023-08-10 18:40
I tried while booted from various installation disks. The change in behaviour appears to start with Mac OS 8.0. So in MacOS versions earlier than Mac OS 8.0 the dropped "CD" can only be removed by dragging it onto the Trash icon.

**Comment by kanjitalk755** [comment] 2023-08-11 01:38
Thank you for testing.
It seems to work fine, so I merge it into the master.

**Closed by kanjitalk755** 2023-08-11 01:38 UTC

**Comment by RonaldPR** [comment] 2023-08-11 08:55
Thanks for your work. I think this is a nice additional feature that will be useful to many users.

**Comment by gingerbeardman** [comment] 2023-08-11 12:55
Thank you so much. Your hard work is very much appreciated.

Though I have not been able to test it, I will do this weekend.

Anyway, I'm happy!

It's a very useful improvement.
