### ISSUE TITLE
Issue (freeze) when launching SheepShaver and BasiliskII in full screen mode

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#76] opened 2021-02-01 20:18 UTC
My latest (31 January 2021) builds of both SheepShaver and BasiliskII freeze when launched in full screen mode.
I get a black screen with beach ball and need to force quit the applications. Another user mentioned a message "Application not responding".
See: https://www.emaculation.com/forum/viewtopic.php?f=20&p=69319#p69319

This seems very similar to the freeze on full screen launch that was discussed here: https://www.emaculation.com/forum/viewtopic.php?f=20&t=10392 and that was solved by you on 25 July 2020.

**Comment by kanjitalk755** [comment] 2021-02-02 01:10
The issue didn't be reproduced.
macOS 10.15.7
Xcode 12.4

I have confirmed that the issue #18 is still fixed in the latest version.
Please let me know if the reproduction conditions are found.

**Comment by RonaldPR** [comment] 2021-02-02 08:15
No specific conditions I can think of.
My 22 September 2020 builds of SheepShaver and BasiliskII launch fine in full screen mode in macOS 10.15.7

The 31 January 2021 builds of both SheepShaver and BasiliskII  freeze with black screen and beach ball when launched in full screen mode.
They do launch normally in window mode and then control-return toggle between window mode and full screen mode works normally.

The builds were available in the forum during one day only. Another user notified me of the issue that could reproduce.

Built with Xcode 12.4 and SDL2.framework version 2.0.14 in macOS 10.15.7.
I needed to change Deployment Target and minimum system version to prevent errors. I changed it to 10.13.

**Comment by kanjitalk755** [comment] 2021-02-02 09:37
Fixed.
The cause was a version upgrade of SDL.

**Closed by kanjitalk755** 2021-02-02 09:37 UTC

**Comment by kanjitalk755** [comment] 2021-02-03 13:32
>I needed to change Deployment Target and minimum system version to prevent errors. I changed it to 10.13.

If you still have this problem in the latest version, please create an issue with details.

**Comment by RonaldPR** [comment] 2021-02-03 14:09
With the 31 January 2020 source, the error happened while building both SheepShaver and BasiliskII. The error mentioned that Deployment Target should be between 10.9 and 11.2.11 (if I remember well). Changing it 10.9 or higher (and adjusting minimum system version accordingly) made the error go away.

With the current source the error appears to be no longer there and Deployment Target can be left at 10.7.

Whatever was changed, it also made the error go away.

Thanks for the speedy fix for the issue with SDL 2.0.14.
