### ISSUE TITLE
Audio crackle with SDL3 enabled

### ISSUE THREAD

**Issue by parkerlreed** [kanjitalk755/macemu#228] opened 2024-12-29 20:09 UTC
BasiliskII latest master with `--with-sdl3`

Audio crackles on start and stop, particularly noticeable for games with a bunch of dialog.

SDL2 build is unaffected.

Arch Linux, sdl3 1:3.1.6-3

Video showing the behavior (first is Infinite Mac showing non popping audio as that's what I had available to compare to)

https://github.com/user-attachments/assets/45a45bff-00f0-478a-99db-5d03679fcdb5

**Comment by parkerlreed** [comment] 2024-12-29 20:10
Comment from @MaddTheSane when I posted on the wrong repo

> It could be because SDL3 dropped support for unsigned 16-bit audio.

**Comment by kanjitalk755** [comment] 2024-12-30 01:19
I tried it with Civilization II but the issue didn't reproduced.
Tell me how to reproduce it.

**Comment by parkerlreed** [comment] 2024-12-30 04:26
BasiliskII SDL3 build running https://archive.org/details/rrk20

System 7.5.5, JIT not enabled

Machine settings

![image](https://github.com/user-attachments/assets/8e91b5df-ddee-4901-b8dd-78d62b642e93)

![image](https://github.com/user-attachments/assets/19c5a1ee-3078-4d2d-a181-5bf73ce7162c)

**Comment by kanjitalk755** [comment] 2024-12-30 11:16
It didn't reproduce on Debian installed SDL-preview-3.1.6.

**Comment by rakslice** [comment] 2024-12-31 07:08
I'm running Ubuntu 24.04, which has pipewire, and doesn't have an available packaged SDL3 afaict, so I'm just running a local build of libsdl-org/SDL@5f25691c856ca53eae322ef8bcfd8b8cbe574989

The challenge was that it didn't even really work well enough on my system to even develop on... You'd get one or two distorted alert sounds or maybe part of one playback of an audio file and then the sound would stop working completely for the rest of the emulator session. And frequently afterward there is a crash or a hang.

It was very reminiscent of the effects of back when the big `switch` in `AudioDispatch()` had an errant `return` in the `if`-clause for closing a mixer.

In short the crackly part of @parkerlreed 's video there was working much better already than what I was seeing :D

But there are two things going on I can see:
- The SDL 3 `stream_func` callback is only delivering the minimum amount of audio requested every call, and is doing probably relatively a lot of processing for a callback, which seems like a recipe for underruns, which explains the crackling noise
- Compared to the existing SDL 2 `stream_func` callback, this one loops on the audio interrupt, and doesn't have a check for `work_size == 0` (i.e. the mac indicating it has no more audio data right now). It sitting there and hammering the audio interrupt over and over waiting for civilization to be restored and deliver bytes of audio (and the lack of protection for an interrupt hitting during some other `Execute68k()` anywhere in `audio.cpp`  explained the bad things happening.

**Comment by rakslice** [comment] 2024-12-31 08:50
Also, it would be nice if this implementation had a working volume control.

That would make it less difficult having to tell what's a playback problem, what's distortion because people can only record it at 100%, and what's just noisy peaky 22050 kHz 8-bit WAVs that aren't going to get much better than they were in the first place ("Ooooh, that Spike, he's done it again!") :P

**Closed** 2024-12-31 11:52 UTC

**Comment by parkerlreed** [comment] 2024-12-31 11:59
@rakslice Thank you! This is indeed sounding great.
