### ISSUE TITLE
Black screen after launching Game intros of AoE 2 Gold

### ISSUE THREAD

**Issue by nexusle** [kanjitalk755/macemu#193] opened 2024-03-15 22:27 UTC
After launching Age of Empires 2 Gold I get a black screen and a not responding SheepShaver. 

It play the two intro videos and after them it should change to game menu but it shows a black screen after short mouse pointer flickering. 

This only happens with the build for Rasperry OS. No matter lite or full. Same with Pi 4 and Pi 5. 

With the macOS build from Emaculation the game runs fine. 

Coukd you please have a look at this?

**Comment by kanjitalk755** [comment] 2024-03-16 10:37
Unfortunately, I don't have the environment to test it on Raspberry Pi 4 or 5.

**Comment by nexusle** [comment] 2024-04-03 15:32
Hi kanjitalk755

I did the work and build a real x86 machine. OS is Debian (latest) without window manager. Also on a x86 machine the behavior is the same. So I hope you can check this with your existing environment.

**Comment by kanjitalk755** [comment] 2024-04-04 11:29
Reproduced.
When I observe it using `gdb`, it seems to be stuck in an infinite loop.
It's difficult to fix because I don't know what the PowerPC binaries on the guest side are doing.

**Comment by nexusle** [comment] 2024-04-04 11:34
As wrote in the initial post, on macOS the game runs fine with SheepShaver loaded from EMaculation. Are these builds based on your code?

**Comment by kanjitalk755** [comment] 2024-04-05 09:17
The download page on the Emaculation forum has the following description:

```
• Version 2.5, 28 February 2024, universal (x86_64 and arm64) from github.com/kanjitalk755/macemu source
```

I'm closing this thread as there is no hope of a fix.

**Comment by kanjitalk755** [comment] 2024-04-05 09:18
The download page on the Emaculation forum has the following description:

```
• Version 2.5, 28 February 2024, universal (x86_64 and arm64) from github.com/kanjitalk755/macemu source
```

I'm closing this thread as there is no hope of a fix.

**Closed by kanjitalk755** 2024-04-05 09:18 UTC
