### ISSUE TITLE
Full screen freezing in Mojave & Catalina

### ISSUE THREAD

**Issue by almeath** [kanjitalk755/macemu#18] opened 2019-10-14 16:58 UTC
The current build is affected by freezing (with black screen and pinwheel) when launched in fullscreen mode. The problem has been detected in macOS Mojave 10.14.5 through to Catalina 10.15 on various models of iMac, MacBook Pro and Mac Mini (and across AMD, Nvidia and Intel graphics).

More information is available here:

https://www.emaculation.com/forum/viewtopic.php?f=20&t=10392&start=25

The freezing occurs when the graphics setting is 'dga', regardless of the specific resolution.

**Comment by kanjitalk755** [comment] 2019-10-15 01:00
I could not reproduce the issue.
Please post the conditions if you can reproduce the issue.

**Comment by kanjitalk755** [comment] 2020-07-25 13:58
Fixed by 1da8385.

**Closed by kanjitalk755** 2020-07-25 13:58 UTC
